module.exports = {
  "A": [
    {
      "team": 247928,
      "promotion": "",
      "lift": "",
      "ranking": 1,
      "P": 2,
      "W": 1,
      "D": 1,
      "L": 0,
      "GF": 3,
      "GA": 1,
      "DIFF": 2,
      "PTS": 4
    },
    {
      "team": 6150,
      "promotion": "",
      "lift": "",
      "ranking": 2,
      "P": 2,
      "W": 1,
      "D": 1,
      "L": 0,
      "GF": 3,
      "GA": 1,
      "DIFF": 2,
      "PTS": 4
    },
    {
      "team": 274526,
      "promotion": "",
      "lift": "",
      "ranking": 3,
      "P": 2,
      "W": 1,
      "D": 0,
      "L": 1,
      "GF": 3,
      "GA": 3,
      "DIFF": 0,
      "PTS": 3
    },
    {
      "team": 564,
      "promotion": "",
      "lift": "",
      "ranking": 4,
      "P": 2,
      "W": 0,
      "D": 0,
      "L": 2,
      "GF": 1,
      "GA": 5,
      "DIFF": -4,
      "PTS": 0
    }
  ],
  "B": [
    {
      "team": 10769,
      "promotion": "",
      "lift": "",
      "ranking": 1,
      "P": 2,
      "W": 1,
      "D": 1,
      "L": 0,
      "GF": 6,
      "GA": 2,
      "DIFF": 4,
      "PTS": 4
    },
    {
      "team": 249514,
      "promotion": "",
      "lift": "up",
      "ranking": 2,
      "P": 2,
      "W": 1,
      "D": 0,
      "L": 1,
      "GF": 4,
      "GA": 6,
      "DIFF": -2,
      "PTS": 3
    },
    {
      "team": 247974,
      "promotion": "",
      "lift": "",
      "ranking": 3,
      "P": 2,
      "W": 0,
      "D": 2,
      "L": 0,
      "GF": 1,
      "GA": 1,
      "DIFF": 0,
      "PTS": 2
    },
    {
      "team": 29385,
      "promotion": "",
      "lift": "down",
      "ranking": 4,
      "P": 2,
      "W": 0,
      "D": 1,
      "L": 1,
      "GF": 1,
      "GA": 3,
      "DIFF": -2,
      "PTS": 1
    }
  ],
  "C": [
    {
      "team": 247960,
      "promotion": "",
      "lift": "up",
      "ranking": 1,
      "P": 2,
      "W": 1,
      "D": 1,
      "L": 0,
      "GF": 2,
      "GA": 0,
      "DIFF": 2,
      "PTS": 4
    },
    {
      "team": 247970,
      "promotion": "",
      "lift": "up",
      "ranking": 2,
      "P": 2,
      "W": 1,
      "D": 0,
      "L": 1,
      "GF": 3,
      "GA": 2,
      "DIFF": 1,
      "PTS": 3
    },
    {
      "team": 250406,
      "promotion": "",
      "lift": "down",
      "ranking": 3,
      "P": 2,
      "W": 1,
      "D": 0,
      "L": 1,
      "GF": 2,
      "GA": 3,
      "DIFF": -1,
      "PTS": 3
    },
    {
      "team": 7366,
      "promotion": "",
      "lift": "down",
      "ranking": 4,
      "P": 2,
      "W": 0,
      "D": 1,
      "L": 1,
      "GF": 0,
      "GA": 2,
      "DIFF": -2,
      "PTS": 1
    }
  ],
  "D": [
    {
      "team": 247956,
      "promotion": "",
      "lift": "",
      "ranking": 1,
      "P": 2,
      "W": 2,
      "D": 0,
      "L": 0,
      "GF": 6,
      "GA": 2,
      "DIFF": 4,
      "PTS": 6
    },
    {
      "team": 251639,
      "promotion": "",
      "lift": "up",
      "ranking": 2,
      "P": 2,
      "W": 1,
      "D": 0,
      "L": 1,
      "GF": 2,
      "GA": 4,
      "DIFF": -2,
      "PTS": 3
    },
    {
      "team": 247993,
      "promotion": "",
      "lift": "down",
      "ranking": 3,
      "P": 2,
      "W": 0,
      "D": 1,
      "L": 1,
      "GF": 1,
      "GA": 2,
      "DIFF": -1,
      "PTS": 1
    },
    {
      "team": 9354,
      "promotion": "",
      "lift": "down",
      "ranking": 4,
      "P": 2,
      "W": 0,
      "D": 1,
      "L": 1,
      "GF": 0,
      "GA": 1,
      "DIFF": -1,
      "PTS": 1
    }
  ],
  "E": [
    {
      "team": 249513,
      "promotion": "",
      "lift": "",
      "ranking": 1,
      "P": 2,
      "W": 1,
      "D": 1,
      "L": 0,
      "GF": 8,
      "GA": 1,
      "DIFF": 7,
      "PTS": 4
    },
    {
      "team": 276433,
      "promotion": "",
      "lift": "",
      "ranking": 2,
      "P": 2,
      "W": 1,
      "D": 0,
      "L": 1,
      "GF": 2,
      "GA": 2,
      "DIFF": 0,
      "PTS": 3
    },
    {
      "team": 12949,
      "promotion": "",
      "lift": "up",
      "ranking": 3,
      "P": 2,
      "W": 1,
      "D": 0,
      "L": 1,
      "GF": 1,
      "GA": 7,
      "DIFF": -6,
      "PTS": 3
    },
    {
      "team": 247971,
      "promotion": "",
      "lift": "down",
      "ranking": 4,
      "P": 2,
      "W": 0,
      "D": 1,
      "L": 1,
      "GF": 2,
      "GA": 3,
      "DIFF": -1,
      "PTS": 1
    }
  ],
  "F": [
    {
      "team": 247072,
      "promotion": "",
      "lift": "up",
      "ranking": 1,
      "P": 2,
      "W": 1,
      "D": 1,
      "L": 0,
      "GF": 4,
      "GA": 1,
      "DIFF": 3,
      "PTS": 4
    },
    {
      "team": 22457,
      "promotion": "",
      "lift": "",
      "ranking": 2,
      "P": 2,
      "W": 1,
      "D": 1,
      "L": 0,
      "GF": 2,
      "GA": 0,
      "DIFF": 2,
      "PTS": 4
    },
    {
      "team": 247968,
      "promotion": "",
      "lift": "down",
      "ranking": 3,
      "P": 2,
      "W": 1,
      "D": 0,
      "L": 1,
      "GF": 1,
      "GA": 2,
      "DIFF": -1,
      "PTS": 3
    },
    {
      "team": 251641,
      "promotion": "",
      "lift": "",
      "ranking": 4,
      "P": 2,
      "W": 0,
      "D": 0,
      "L": 2,
      "GF": 1,
      "GA": 5,
      "DIFF": -4,
      "PTS": 0
    }
  ],
  "G": [
    {
      "team": 247994,
      "promotion": "",
      "lift": "",
      "ranking": 1,
      "P": 2,
      "W": 2,
      "D": 0,
      "L": 0,
      "GF": 3,
      "GA": 0,
      "DIFF": 3,
      "PTS": 6
    },
    {
      "team": 246548,
      "promotion": "",
      "lift": "",
      "ranking": 2,
      "P": 2,
      "W": 1,
      "D": 0,
      "L": 1,
      "GF": 1,
      "GA": 1,
      "DIFF": 0,
      "PTS": 3
    },
    {
      "team": 6888,
      "promotion": "",
      "lift": "",
      "ranking": 3,
      "P": 2,
      "W": 0,
      "D": 1,
      "L": 1,
      "GF": 3,
      "GA": 4,
      "DIFF": -1,
      "PTS": 1
    },
    {
      "team": 247931,
      "promotion": "",
      "lift": "",
      "ranking": 4,
      "P": 2,
      "W": 0,
      "D": 1,
      "L": 1,
      "GF": 3,
      "GA": 5,
      "DIFF": -2,
      "PTS": 1
    }
  ],
  "H": [
    {
      "team": 247958,
      "promotion": "",
      "lift": "",
      "ranking": 1,
      "P": 2,
      "W": 2,
      "D": 0,
      "L": 0,
      "GF": 5,
      "GA": 2,
      "DIFF": 3,
      "PTS": 6
    },
    {
      "team": 24447,
      "promotion": "",
      "lift": "up",
      "ranking": 2,
      "P": 2,
      "W": 1,
      "D": 0,
      "L": 1,
      "GF": 5,
      "GA": 5,
      "DIFF": 0,
      "PTS": 3
    },
    {
      "team": 2553,
      "promotion": "",
      "lift": "down",
      "ranking": 3,
      "P": 2,
      "W": 0,
      "D": 1,
      "L": 1,
      "GF": 2,
      "GA": 3,
      "DIFF": -1,
      "PTS": 1
    },
    {
      "team": 321914,
      "promotion": "",
      "lift": "down",
      "ranking": 4,
      "P": 2,
      "W": 0,
      "D": 1,
      "L": 1,
      "GF": 0,
      "GA": 2,
      "DIFF": -2,
      "PTS": 1
    }
  ]
}