module.exports = [
  {
    "tid": 21389,
    "iid": 9077809,
    "statePhase": "NON_START",
    "homeId": 10759,
    "awayId": 247967,
    "homeName": "苏格兰",
    "awayName": "乌克兰",
    "kickOffTime": 1654065900,
    "roundType": "qualification",
    "roundGroup": "B",
    "roundName": "World Cup, qualifica",
    "sortId": 1,
    "scoreList": []
  },
  {
    "tid": 21389,
    "iid": 9106608,
    "statePhase": "NON_START",
    "homeId": 29385,
    "awayId": 247967,
    "homeName": "威尔士",
    "awayName": "乌克兰",
    "kickOffTime": 1654401600,
    "roundType": "qualification",
    "roundGroup": "B",
    "roundName": "World Cup, qualifica",
    "sortId": 2,
    "scoreList": []
  },
  {
    "tid": 21582,
    "iid": 9105316,
    "statePhase": "NON_START",
    "homeId": 10863,
    "awayId": 251639,
    "homeName": "阿联酋",
    "awayName": "澳大利亚",
    "kickOffTime": 1654624800,
    "roundType": "qualification",
    "roundGroup": "D",
    "roundName": "World Cup, qualifica",
    "sortId": 3,
    "scoreList": []
  },
  {
    "tid": 8972,
    "iid": 9114511,
    "statePhase": "NON_START",
    "homeId": 251639,
    "awayId": 10772,
    "homeName": "澳大利亚",
    "awayName": "秘鲁",
    "kickOffTime": 1655100000,
    "roundType": "qualification",
    "roundGroup": "D",
    "roundName": "World Cup, qualifica",
    "sortId": 4,
    "scoreList": []
  },
  {
    "tid": 8972,
    "iid": 9074069,
    "statePhase": "NON_START",
    "homeId": 12949,
    "awayId": 314718,
    "homeName": "哥斯达黎加",
    "awayName": "纽西兰",
    "kickOffTime": 1655186400,
    "roundType": "qualification",
    "roundGroup": "E",
    "roundName": "World Cup, qualifica",
    "sortId": 5,
    "scoreList": []
  }
]